### ISSUE TITLE
Dismiss notification icon not working

### ISSUE THREAD

**Issue by MatthewMoore2529** [benJervis/civitas-crm#13]
When you select the dismiss notification icon, you get page saying that "The page you were looking for doesn't exist"

**Comment by ben-jervis-old** [comment]
The path is 'resolve' rather than 'dismiss' so this path helper needs changing.

https://github.com/benJervis/civitas-crm/blob/3957a6861799bd3a75cacc75b7b6c2b70fbe57e9/app/views/dashboard/_notifications.html.erb#L18
