### ISSUE TITLE
Settings icon not working

### ISSUE THREAD

**Issue by MatthewMoore2529** [benJervis/civitas-crm#14]
Settings icon doesn't link anywhere

**Comment by ben-jervis-old** [comment]
Just link this to the user_path

https://github.com/benJervis/civitas-crm/blob/3957a6861799bd3a75cacc75b7b6c2b70fbe57e9/app/views/partials/_navbar.html.erb#L48

**Comment by ben-jervis-old** [comment]
Also put tooltips on the notifications and contact icons
