### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by JRNicholls** [benJervis/civitas-crm#18]
When passwords don't match the button becomes inactive but nothing else happens.

**Comment by ben-jervis-old** [comment]
Is this on the "I forgot my password" page, or on the "Update Password" from inside user show?

**Comment by JRNicholls** [comment]
When you request a reset password link. The page that the email directs you too.

**Comment by ben-jervis-old** [comment]
Ok cool, will investigate

**Comment by JRNicholls** [comment]
Also if password is too short it also disables the button.

**Comment by ben-jervis-old** [comment]
Looks like the update method in password_resets just needs an else added
